### PR TITLE
Updated src/Test/Test.py

### PR DESCRIPTION
**Pull request by Dadaji18**
Made changes in src/Test/Test.py to return time in hours for time exceeding 59 minutes 59 seconds

### CODE REVIEW

**Comment by akstron** [comment]
Kindly create a separate converter function which take input in seconds and gives converted output. Use it to print result on terminal.

**Comment by Dadaji18** [comment]
Added converter function to return time in hours for time exceeding 59 minutes 59 seconds

**Comment by akstron** [comment]
We can have a converter function instead of print_rem_time, which would return time in hours, minutes and seconds. Then we can print it in get_rem_time. Also we can create a separate utils files for this converter.

**Comment by Dadaji18** [comment]
Please check the above commit.

**Pull request merged**
